name: Update M3U Playlists

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir çalışır.
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  update-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 aiohttp

      - name: Run Python script for movies
        run: python DiziFunFilm.py

      - name: Run Python script for TV series
        run: python DiziFunDizi.py

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add filmfun.m3u dizifun.m3u
          git commit -m "Güncellenmiş M3U dosyaları" || echo "Değişiklik yok"
          # Yeni eklenen satır: Push işleminden önce en son değişiklikleri çeker
          git pull --rebase origin main || echo "Ana depoda yeni değişiklikler yok, devam ediliyor"
          git push
